# Generated by Django 4.2.24 on 2026-01-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio_sesion', '0002_alter_rol_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('certificado', 'Certificado'), ('boletin', 'Boletín'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(help_text='Ej: Certificado de notas 2025', max_length=100)),
                ('archivo', models.FileField(upload_to='documentos_usuarios/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'documento_usuario',
                'managed': True,
            },
        ),
    ]
