# Generated by Django 4.2.24 on 2026-01-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del curso', max_length=150)),
                ('descripcion', models.TextField(help_text='Descripción general del curso')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=20)),
                ('duracion', models.CharField(help_text='Ej: 40 horas', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cursos',
                'managed': True,
            },
        ),
    ]
