# Generated by Django 4.2.24 on 2026-02-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_cursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('noticia', 'Última Noticia'), ('inscripcion', 'Inscripción Abierta'), ('curso', 'Próximo Curso')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenidos/')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Usado para inscripciones y cursos', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Solo para inscripciones', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cupos', models.PositiveIntegerField(blank=True, help_text='Solo para cursos', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
