# Generated by Django 4.2.24 on 2026-02-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={},
        ),
        migrations.AddField(
            model_name='contenido',
            name='icono',
            field=models.CharField(blank=True, help_text='Solo para cursos (ej: fa-solid fa-book)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='cupos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
