# Generated by Django 4.2.24 on 2026-02-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_contenido_options_contenido_icono_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='contenido',
            table='administrador_contenido',
        ),
    ]
