# Generated by Django 4.2.24 on 2026-02-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0004_usuario_reset_token_usuario_reset_token_expira'),
        ('administrador', '0005_alter_contenido_options_alter_contenido_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('inscrito', 'Inscrito'), ('retirado', 'Retirado'), ('finalizado', 'Finalizado')], default='inscrito', max_length=15)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='administrador.cursos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'inscripciones',
                'managed': True,
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
