# Generated by Django 4.2.24 on 2026-02-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('pre_inscrito', 'Pre-inscrito'), ('inscrito', 'Inscrito'), ('retirado', 'Retirado'), ('finalizado', 'Finalizado')], default='inscrito', max_length=15),
        ),
    ]
