# Generated by Django 4.2.24 on 2025-11-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=255)),
                ('id_tipo_documento', models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.tipodocumento')),
                ('id_tipo_rol', models.ForeignKey(db_column='id_tipo_rol', default=2, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
