# Generated by Django 4.2.24 on 2026-01-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': False},
        ),
    ]
