# Generated by Django 4.2.24 on 2026-01-24 16:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_alter_rol_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
