# Generated by Django 4.2.24 on 2026-01-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0003_alter_usuario_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
