# Generated by Django 4.2.24 on 2026-01-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_clase', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=10)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'clases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id_tipo_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_archivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id_trabajos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_entrega', models.DateField()),
                ('clase', models.ForeignKey(blank=True, db_column='clase_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'trabajos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InscritoClase',
            fields=[
                ('id_inscripcion_clase', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, db_column='fecha_inscripcion')),
                ('clase', models.ForeignKey(blank=True, db_column='clase_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'inscrito_clase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComentarioClase',
            fields=[
                ('id_comentario_clase', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='clases.clase')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_clase', to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'comentarios_clase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClaseVirtual',
            fields=[
                ('id_clase_virtual', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_de_clase', models.DateTimeField(db_column='fecha_de_clase')),
                ('url_clase', models.CharField(db_column='url_clase', max_length=255)),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='clases_virtuales', to='clases.clase')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='clases_virtuales', to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'clases_virtuales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('url_archivo', models.FileField(upload_to='archivos/')),
                ('fecha_subido', models.DateTimeField(auto_now_add=True)),
                ('tipo_archivo', models.ForeignKey(db_column='tipo_archivo_id', on_delete=django.db.models.deletion.CASCADE, to='clases.tipoarchivo')),
                ('trabajo', models.ForeignKey(db_column='id_trabajos', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='clases.trabajos')),
            ],
            options={
                'db_table': 'archivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EntregaTrabajo',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, db_column='fecha_entrega')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('No entregado', 'No entregado'), ('Entregado con retardo', 'Entregado con retardo')], default='Pendiente', max_length=30)),
                ('archivo', models.ForeignKey(blank=True, db_column='archivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.archivo')),
                ('estudiante', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
                ('trabajo', models.ForeignKey(db_column='id_trabajos', on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='clases.trabajos')),
            ],
            options={
                'db_table': 'entrega_trabajo',
                'managed': True,
                'unique_together': {('trabajo', 'estudiante')},
            },
        ),
    ]
