# Generated by Django 4.2.24 on 2025-12-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio_sesion', '0002_usuario_estado_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_clase', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=10)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'clases',
            },
        ),
        migrations.CreateModel(
            name='InscritoClase',
            fields=[
                ('id_inscripcion_clase', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, db_column='fecha_inscripcion')),
                ('clase', models.ForeignKey(db_column='clase_id', on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'inscrito_clase',
            },
        ),
    ]
