# Generated by Django 4.2.24 on 2026-01-04 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='trabajo',
        ),
        migrations.RemoveField(
            model_name='entregatrabajo',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivo',
            name='entrega',
            field=models.ForeignKey(blank=True, db_column='entrega_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='clases.entregatrabajo'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='url_archivo',
            field=models.FileField(upload_to='entregas/'),
        ),
    ]
