# Generated by Django 4.2.24 on 2025-12-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
