# Generated by Django 4.2.24 on 2026-01-04 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_remove_archivo_trabajo_remove_entregatrabajo_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoTrabajo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='trabajos/')),
                ('fecha_subido', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(db_column='trabajo_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos_trabajo', to='clases.trabajos')),
            ],
            options={
                'db_table': 'archivo_trabajo',
                'managed': True,
            },
        ),
    ]
