# Generated by Django 4.2.24 on 2025-12-10 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_usuario_estado_usuario_fecha_nacimiento'),
        ('clases', '0002_clase_descripcion_clase_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('url_archivo', models.FileField(max_length=255, upload_to='archivos/')),
                ('fecha_subido', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archivo',
            },
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('id_tipo_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_archivo',
            },
        ),
        migrations.AlterField(
            model_name='inscritoclase',
            name='clase',
            field=models.ForeignKey(blank=True, db_column='clase_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.clase'),
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id_trabajos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('No entregado', 'No entregado'), ('Entregado Con Retardo', 'Entregado Con Retardo')], default='Pendiente', max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_entrega', models.DateField()),
                ('archivos', models.ForeignKey(db_column='archivos_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.archivo')),
                ('clase', models.ForeignKey(blank=True, db_column='clase_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'trabajos',
            },
        ),
        migrations.AddField(
            model_name='archivo',
            name='tipo_archivo',
            field=models.ForeignKey(db_column='tipo_archivo_id', on_delete=django.db.models.deletion.CASCADE, to='clases.tipoarchivo'),
        ),
    ]
