# Generated by Django 4.2.24 on 2026-01-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_archivotrabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='entrega',
        ),
        migrations.AddField(
            model_name='archivo',
            name='trabajo',
            field=models.ForeignKey(db_column='id_trabajos', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='clases.trabajos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivo',
            name='url_archivo',
            field=models.FileField(upload_to='archivos/'),
        ),
        migrations.DeleteModel(
            name='ArchivoTrabajo',
        ),
    ]
