# Generated by Django 4.2.24 on 2025-12-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_archivo_tipoarchivo_alter_inscritoclase_clase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
