# Generated by Django 4.2.24 on 2025-12-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_archivo_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'managed': False},
        ),
    ]
