# Generated by Django 4.2.24 on 2026-01-04 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_remove_archivo_entrega_archivo_trabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEntrega',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='entregas/')),
                ('fecha_subido', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='clases.entregatrabajo')),
                ('tipo_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.tipoarchivo')),
            ],
            options={
                'db_table': 'archivo_entrega',
                'managed': True,
            },
        ),
    ]
