# Generated by Django 4.2.24 on 2026-01-20 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_alter_rol_options'),
        ('clases', '0005_archivoentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionTrabajo',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('entrega', models.OneToOneField(db_column='id_entrega', on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='clases.entregatrabajo')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'calificacion_trabajo',
                'managed': True,
            },
        ),
    ]
