# Generated by Django 4.2.24 on 2025-12-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_usuario_estado_usuario_fecha_nacimiento'),
        ('clases', '0005_alter_archivo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajos',
            name='estado',
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='archivos',
            field=models.ForeignKey(blank=True, db_column='archivos_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.archivo'),
        ),
        migrations.CreateModel(
            name='EntregaTrabajo',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, db_column='fecha_entrega')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado'), ('No entregado', 'No entregado'), ('Entregado con retardo', 'Entregado con retardo')], default='Pendiente', max_length=30)),
                ('archivo', models.ForeignKey(blank=True, db_column='archivo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clases.archivo')),
                ('estudiante', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.usuario')),
                ('trabajo', models.ForeignKey(db_column='trabajo_id', on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='clases.trabajos')),
            ],
            options={
                'db_table': 'entrega_trabajo',
                'unique_together': {('trabajo', 'estudiante')},
            },
        ),
    ]
