# Generated by Django 4.2.24 on 2025-12-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0006_remove_trabajos_estado_alter_trabajos_archivos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseVirtual',
            fields=[
                ('id_clase_virtual', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_de_clase', models.DateTimeField(db_column='fecha_de_clase')),
                ('url_clase', models.CharField(db_column='url_clase', max_length=255)),
            ],
            options={
                'db_table': 'clases_virtuales',
                'managed': False,
            },
        ),
    ]
