# Generated by Django 4.2.24 on 2025-12-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_clasevirtual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasevirtual',
            options={},
        ),
    ]
