# Generated by Django 4.2.24 on 2025-12-22 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0002_usuario_estado_usuario_fecha_nacimiento'),
        ('clases', '0008_alter_clasevirtual_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasevirtual',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='ComentarioClase',
            fields=[
                ('id_comentario_clase', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='clases.clase')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_clase', to='inicio_sesion.usuario')),
            ],
            options={
                'db_table': 'comentarios_clase',
            },
        ),
    ]
